#! /usr/bin/env bash

# Jules GILET <jules.gilet@curie.fr>

# custom pipeline for the TCR (and BCR) repertoire analysis of single cell 10x 3' libraries
# has been optimized for TCR
# repertoire analysis is done with mixcr

# requires preprocess with ikura
# requires (clean trimmed) fastq gzipped files
# requires python-3.6.5 or above
# requires umi_tools 0.5.4 or above
# requires mixcr 2.1.12 or above
# requires R-3.5.0 or above

# options
VERSION="v1.0"
EXECDIR=${PWD}
SCRIPTDIR="$(dirname "$0")"


usage(){

	echo ""
	echo "Tobiko ${VERSION}"
	echo "Usage:"
	echo "$0	[-n|--skip-rebarcoding] (optional, mostly for debugging)
		[-s|--specy] <specy:hs|HomoSapiens|mmu|MusMusculus>
		[-c|--chains] <anyof:IGH,IGL,IGK,TRA,TRB,TRG,TRD,IGH,IGL,IGK> (optional, default is TRA,TRB)
		[-i|--ikura] <ikuraOutputPath>
		[-u|--umithreshold] <threshold> (optional, default is 1)
		[-t|--threads] <coresNb> (optional, default is 16)

		Directory should be specified as absolute path.
		"

        exit 0


}

if [ $# -eq 0 ]; then

	usage

fi

cd "${SCRIPTDIR}"
source dependencies.txt
source sources/pydep

if ! sources/checkdep; then
        exit 1
fi


# options
BC="T"
CORES=16
UTHR=1
CHAINS="TRA,TRB"

while [ "$#" -gt 0 ]; do
        case "$1" in

                -h|--help)	usage;;

		-n|--skip-rebarcoding) BC="F"; shift 1;;
		-s|--specy) SPECY="$2"; shift 2;;
		-c|--chains) CHAINS="$2"; shift 2;;
                -i|--ikura) IKURA="$2"; shift 2;;
		-u|--umithreshold) UTHR="$2"; shift 2;;
		-t|--threads) CORES="$2"; shift 2;;

                -*|--*) echo "unknown option: $1" >&2; exit 1;;

        esac
done


# exec
SECONDS=0

# setup directories
if [ ! -d "$IKURA" ]; then
        echo "Error: Ikura output path doesn't exist"
	exit 1
fi

cd ${IKURA}

PREFIX=${PWD##*/}
FASTQDIR=${IKURA}/fastq
LOGDIR=${IKURA}/logs
READ1=${FASTQDIR}/*trimmed_R1.fastq.gz
READ2=${FASTQDIR}/*trimmed_R2.fastq.gz
WHITELIST=$(ls ${LOGDIR}/whitelist_*.txt)
OUTIKURA=${IKURA}/outs

if [ ! -d "tobiko" ]; then
        mkdir tobiko
fi

OUTPATH=${IKURA}/tobiko

# data process
echo "job started on" $(date)

if [ "${BC}" = "T" ]
then
	echo "extracting barcodes..."
	${UMITOOLS} extract --bc-pattern=CCCCCCCCCCCCCCCCNNNNNNNNNN --stdin ${READ1} --stdout ${FASTQDIR}/${PREFIX}_barcoded_R1.fastq.gz --read2-in ${READ2} --read2-out=${FASTQDIR}/${PREFIX}_barcoded_R2.fastq.gz --filter-cell-barcode --whitelist=${WHITELIST}

fi

echo "aligning reads..."
${MIXCR} align -f --report ${LOGDIR}/report_mixcrAlign_${PREFIX}.txt --species ${SPECY} --parameters rna-seq -t ${CORES} --save-description ${FASTQDIR}/${PREFIX}_barcoded_R2.fastq.gz ${OUTPATH}/alignments_${PREFIX}.vdjca

echo "creating tables..."
${MIXCR} assemble -f --index ${OUTPATH}/indexFile_${PREFIX} --report ${LOGDIR}/report_mixcrAssembl_${PREFIX}.txt ${OUTPATH}/alignments_${PREFIX}.vdjca ${OUTPATH}/clones_${PREFIX}.clns
${MIXCR} exportAlignments -f -cloneId ${OUTPATH}/indexFile_${PREFIX} -descrR1 ${OUTPATH}/alignments_${PREFIX}.vdjca ${OUTPATH}/alignments_${PREFIX}.txt
${MIXCR} exportClones -f --chains ${CHAINS} ${OUTPATH}/clones_${PREFIX}.clns ${OUTPATH}/clones_${PREFIX}_ALLraw.txt
${MIXCR} exportClones -f -cloneId -count -fraction -vgenes -dgenes -jgenes -nFeature CDR3 -aaFeature CDR3 --filter-out-of-frames --minimal-clone-count ${UTHR} --chains TRA,TRB ${OUTPATH}/clones_${PREFIX}.clns ${OUTPATH}/clonesSummary_${PREFIX}.tsv
${MIXCR} exportClones -f -cloneId -count -fraction -vgenes -dgenes -jgenes -nFeature CDR3 -aaFeature CDR3 --filter-out-of-frames --minimal-clone-count ${UTHR} --chains TRA ${OUTPATH}/clones_${PREFIX}.clns ${OUTPATH}/clonesTCRA_${PREFIX}.tsv
${MIXCR} exportClones -f -cloneId -count -fraction -vgenes -dgenes -jgenes -nFeature CDR3 -aaFeature CDR3 --filter-out-of-frames --minimal-clone-count ${UTHR} --chains TRB ${OUTPATH}/clones_${PREFIX}.clns ${OUTPATH}/clonesTCRB_${PREFIX}.tsv

awk '{split($2, aay, "_"); {print $1, " ", aay[2]}}' ${OUTPATH}/alignments_${PREFIX}.txt | grep -v "^SN" | sed 1d | sort -k 2 > ${OUTPATH}/clonespercells.tsv 
awk -F "\t" '{print $1, $4 $6 "-" $8}' ${OUTPATH}/clonesSummary_${PREFIX}.tsv | sed 1d | sort -u | sed "s/,/|/g" > ${OUTPATH}/clonesids.tsv
join -j 1 -o 1.2 2.2 <(sort -k1 ${OUTPATH}/clonespercells.tsv) <(sort -k1 ${OUTPATH}/clonesids.tsv) > ${OUTPATH}/clonetable_${PREFIX}.tsv
# rm ${OUTPATH}/clonespercells.tsv ${OUTPATH}/clonesids.tsv ${OUTPATH}/alignments_${PREFIX}.vdjca ${OUTPATH}/alignments_${PREFIX}.txt ${OUTPATH}/clones_${PREFIX}.clns

echo "exporting data to the matrix..."
${RPATH}/Rscript ${SCRIPTDIR}/sources/postProcess ${OUTPATH}/clonetable_${PREFIX}.tsv ${OUTIKURA} ${OUTPATH}


END=${SECONDS}

echo "job complete on " $(date)
echo "total execution time (min): " $((${END} / 60))

exit 0
